# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f8f0db778fc9f33036889dc564c1e1292c69f36dbc795358566fb27040c9c3f0891aca080e6d18fedb2626b91660fc831aee783b81ee644780b621e05e6820d

test:
  secret_key_base: b36aca72fd6e231552fa83deec1c1465ab1d0d3c77599b3495b4fadcda106b67fedcada7698bafdd1eed813a889e793d44d70ad6a66d270a4236fe687bb0956f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
